spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/afb_dotations_telephoniques}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

logging:
  level:
    com.afriland.dottel: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:3000"
        allowed-methods: GET