@startuml
title <size:24>Reporting</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("DottelApplication_boundary", "DottelApplication", $tags="") {
  Container_Boundary("DottelApplication.DottelApplication_boundary", "DottelApplication", $tags="") {
    Component(DottelApplication.DottelApplication.Audit, "Audit", $techn="Module", $descr="", $tags="", $link="")
    Component(DottelApplication.DottelApplication.Beneficiaires, "Beneficiaires", $techn="Module", $descr="", $tags="", $link="")
    Component(DottelApplication.DottelApplication.Processus, "Processus", $techn="Module", $descr="", $tags="", $link="")
    Component(DottelApplication.DottelApplication.Reporting, "Reporting", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(DottelApplication.DottelApplication.Beneficiaires, DottelApplication.DottelApplication.Audit, "depends on", $techn="", $tags="", $link="")
Rel(DottelApplication.DottelApplication.Reporting, DottelApplication.DottelApplication.Audit, "uses", $techn="", $tags="", $link="")
Rel(DottelApplication.DottelApplication.Reporting, DottelApplication.DottelApplication.Beneficiaires, "uses", $techn="", $tags="", $link="")
Rel(DottelApplication.DottelApplication.Reporting, DottelApplication.DottelApplication.Processus, "uses", $techn="", $tags="", $link="")
Rel(DottelApplication.DottelApplication.Processus, DottelApplication.DottelApplication.Audit, "depends on", $techn="", $tags="", $link="")
Rel(DottelApplication.DottelApplication.Processus, DottelApplication.DottelApplication.Beneficiaires, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml